package org.codegen.format

data class CodeFormatRules(
    val filePrefix: () -> String = { "" },
    val headersPostfix: String = "\n\n",
    val entitiesSeparator: String = "\n",
) {
    companion object {
        val KOTLIN = CodeFormatRules(
            filePrefix = { "// Generated by DTO-Codegen\npackage \${PACKAGE_NAME}\n\n".substituteEnvVars() },
            headersPostfix = "\n\n",
            entitiesSeparator = "\n\n",
        )

        val PYTHON = CodeFormatRules(
            filePrefix = { "# Generated by DTO-Codegen\n\n" },
            headersPostfix = "\n\n\n",
            entitiesSeparator = "\n\n\n",
        )
    }
}
