stages:
  - build
  - test
  - registry-image

variables:
  IMAGE: '$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG'
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

gradle:
  stage: build
  image: openjdk:17
  only:
    - master
  cache:
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - .gradle/
    - key: $CI_PIPELINE_ID
      policy: push
      paths:
        - build/
  script:
    - ./gradlew --warning-mode all ktlintCheck
    - ./gradlew jibBuildTar --image=$IMAGE

run-tests:
  stage: test
  image: amazoncorretto:17-alpine
  only:
    variables:
      # run for protected branches only
      - $CI_COMMIT_REF_PROTECTED == 'true'
  cache:
    - key: $CI_COMMIT_REF_SLUG
      policy: pull
      paths:
        - .gradle/
    - key: $CI_PIPELINE_ID
      policy: pull
      paths:
        - build/
  script:
    - ./gradlew jacocoTestReport
    - awk -F, '{ lines += $8 + $9; covered += $9 } END { print covered, "/", lines, " lines covered"; print 100*covered/lines, "% covered" }' build/reports/jacoco/test/jacocoTestReport.csv
  coverage: '/([\d,.]+) \% covered/'

run-generated-code-tests:
  stage: test
  image: docker:25
  services:
    - docker:25-dind
  script:
    - cd generatedCodeTests
    - sh run_all.sh

docker-push:
  stage: registry-image
  image: docker:stable
  only:
    - master
  cache:
    key: $CI_PIPELINE_ID
    policy: pull
    paths:
      - build/
  services:
    - docker:stable-dind
  variables:
    GIT_STRATEGY: none
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker load --input build/jib-image.tar
    - docker push $IMAGE
