stages:
  - build
  - test
  - publish

variables:
  IMAGE: '$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG'
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

gradle:
  stage: build
  image: openjdk:21
  only:
    variables:
      # run for protected branches only
      - $CI_COMMIT_REF_PROTECTED == 'true'
  cache:
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - .gradle/
    - key: $CI_PIPELINE_ID
      policy: push
      paths:
        - build/
  script:
    - ./gradlew --warning-mode all ktlintCheck
    - ./gradlew jibBuildTar --image=$IMAGE

run-tests:
  stage: test
  image: openjdk:21
  only:
    variables:
      # run for protected branches only
      - $CI_COMMIT_REF_PROTECTED == 'true'
  cache:
    - key: $CI_COMMIT_REF_SLUG
      policy: pull
      paths:
        - .gradle/
    - key: $CI_PIPELINE_ID
      policy: pull
      paths:
        - build/
  script:
    - ./gradlew jacocoTestReport
    - awk -F, '{ lines += $8 + $9; covered += $9 } END { print covered, "/", lines, " lines covered"; print 100*covered/lines, "% covered" }' build/reports/jacoco/test/jacocoTestReport.csv
  coverage: '/([\d,.]+) \% covered/'

run-tests-PyApiClientGenerator:
  stage: test
  image: docker:25
  services:
    - docker:25-dind
  artifacts:
    name: coverage
    paths:
      - generatedCodeTests/PyApiClientGenerator/htmlcov/
  script:
    - cd generatedCodeTests/PyApiClientGenerator
    - sh run.sh
  coverage: '/TOTAL.*\s(\d+%)/'

run-tests-PyApiAsyncClientGenerator:
  stage: test
  image: docker:25
  services:
    - docker:25-dind
  artifacts:
    name: coverage
    paths:
      - generatedCodeTests/PyApiAsyncClientGenerator/htmlcov/
  script:
    - cd generatedCodeTests/PyApiAsyncClientGenerator
    - sh run.sh
  coverage: '/TOTAL.*\s(\d+%)/'

run-tests-PyDataclassGenerator:
  stage: test
  image: docker:25
  services:
    - docker:25-dind
  artifacts:
    name: coverage
    paths:
      - generatedCodeTests/PyDataclassGenerator/htmlcov/
  script:
    - cd generatedCodeTests/PyDataclassGenerator
    - sh run.sh
  coverage: '/TOTAL.*\s(\d+%)/'

run-tests-PyMarshmallowDataclassGenerator:
  stage: test
  image: docker:25
  services:
    - docker:25-dind
  artifacts:
    name: coverage
    paths:
      - generatedCodeTests/PyMarshmallowDataclassGenerator/htmlcov/
  script:
    - cd generatedCodeTests/PyMarshmallowDataclassGenerator
    - sh run.sh
  coverage: '/TOTAL.*\s(\d+%)/'

run-tests-PyDjangoModelGenerator:
  stage: test
  image: docker:25
  services:
    - docker:25-dind
  artifacts:
    name: migrations
    paths:
      - generatedCodeTests/PyDjangoModelGenerator/app/migrations/
  script:
    - cd generatedCodeTests/PyDjangoModelGenerator
    - sh run.sh
  coverage: '/TOTAL.*\s(\d+%)/'

publish-distro:
  stage: publish
  image: openjdk:21
  only:
    variables:
      # run for protected branches only
      - $CI_COMMIT_REF_PROTECTED == 'true'
  cache:
    key: $CI_PIPELINE_ID
    policy: pull
    paths:
      - build/
  artifacts:
    name: distribution
    paths:
      - build/distributions/
  script:
    - ./gradlew build


docker-push:
  stage: publish
  image: docker:stable
  only:
    variables:
      # run for protected branches only
      - $CI_COMMIT_REF_PROTECTED == 'true'
  cache:
    key: $CI_PIPELINE_ID
    policy: pull
    paths:
      - build/
  services:
    - docker:stable-dind
  variables:
    GIT_STRATEGY: none
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker load --input build/jib-image.tar
    - docker push $IMAGE
