package org.codegen.utils

import org.codegen.AppConfiguration
import org.codegen.utils.EnvironmentUtils.Companion.substituteEnvVariables

data class CodeFormatRules(
    val filePrefix: () -> String,
    val headersPostfix: String,
    val entitiesSeparator: String,
    val entityName: (String) -> String,
) {
    companion object {
        private val HEADER = "Auto-generated by ${AppConfiguration.name} ${AppConfiguration.version}, do not edit"

        val KOTLIN =
            CodeFormatRules(
                filePrefix = { substituteEnvVariables("// $HEADER\npackage \${PACKAGE_NAME}\n\n") },
                headersPostfix = "\n\n",
                entitiesSeparator = "\n\n",
                entityName = { name -> name.camelCase() },
            )

        val PYTHON =
            CodeFormatRules(
                filePrefix = { "# $HEADER\n# flake8: noqa\n" },
                headersPostfix = "\n\n\n",
                entitiesSeparator = "\n\n\n",
                entityName = { name -> name.camelCase() },
            )
    }
}
