version: '3'
services:

  py_api_client_python_3_10:
    build:
      context: .
    links:
      - mock_server
    environment:
      BASE_URL: 'http://mock_server'
    volumes:
      - './htmlcov/:/app/htmlcov/'

  mock_server:
    build:
      context: ../sidecars/mock_server
