services:

  py_django_model:
    container_name: $CONTAINER_NAME
    build:
      context: .
      args:
        IMAGE: $IMAGE
    volumes:
      - './entities/migrations/:/testproject/entities/migrations/'
      - './openapi/migrations/:/testproject/openapi/migrations/'
