package generators

import org.codegen.common.dto.*
import java.util.*

class PyDataclassCodeGenerator : CodeGeneratorInterface {
    private val dtypeAttrs = mutableMapOf<String, DtypeAttributesMapping>()
    private val entities = mutableListOf<Entity>()
    private val headers = mutableListOf(
        "# Generated by DTO-Codegen on ${Date()}",
        "",
        "from dataclasses import dataclass, field",
        "import typing as t",
    )

    override fun addEntity(entity: Entity) {
        if (!entities.contains(entity))
            entities.add(entity)
    }

    override fun addDtypeExtension(dtype: String, attrs: DtypeAttributesMapping) {
        dtypeAttrs[dtype] = attrs
    }

    private fun addHeader(str: String) {
        if (!headers.contains(str))
            headers.add(str)
    }

    private fun buildEntity(entity: Entity): String {
        val preLines = mutableListOf<String>()
        val lines = mutableListOf(
            "@dataclass",
            "class ${entity.name.toCamelCase()}:",
        )

        entity.description?.also {
            lines.add("    \"\"\"")
            lines.add("    " + entity.description)
            lines.add("    \"\"\"")
        }

        for (field in entity.fields) {
            val dtypeProps = dtypeAttrs[field.dtype]
            val fieldName = field.name.toSnakeCase()
            val attrs = mutableMapOf<String, String>()

            requireNotNull(dtypeProps) {"Missing extension for dtype '${field.dtype}'"}

            dtypeProps.requiredHeader?.let {
                addHeader(it)
            }

            var definition = dtypeProps.definition

            field.default?.let { raw ->
                dtypeProps.toGeneratedValue(raw).also {
                    if ("[".contains(it[0])) {
                        // complex value (list/map/etc) should be inserted via function above class
                        val callableName = "default_$fieldName"
                        preLines.add("def $callableName():")
                        preLines.add("    return $it\n\n")
                        attrs["default_factory"] = callableName
                    } else {
                        // simple value -> insert inline
                        attrs["default"] = it
                    }
                }
            }

            field.longDescription?.let {
                lines.add("    # $it")
            }

            if (field.nullable)
                definition = "t.Optional[$definition]"
                if (field.default == null)
                    attrs["default"] = "None"

            val expression = if (attrs.size == 1 && attrs.containsKey("default")) {
                // = defaultValue
                attrs.getValue("default")
            } else {
                // = field(param1=..., param2=...)
                val attrsString = attrs.map { entry -> "${entry.key}=${entry.value}" }.joinToString()
                "field($attrsString)"
            }

            lines.add("    ${field.name.toSnakeCase()}: $definition = $expression")
        }

        return (preLines + lines).joinToString("\n")
    }

    override fun build(): String {
        val builtEntities = entities.map { buildEntity(it) }

        return headers.joinToString("\n", postfix = "\n\n\n") +
                builtEntities.joinToString("\n\n\n", postfix = "\n")
    }
}