package generators

import org.codegen.common.dto.*
import java.util.*

class PyDataclassCodeGenerator : CodeGeneratorInterface {
    private val dtypeAttrs = mutableMapOf<String, DtypeAttributesMapping>()
    private val entities = mutableListOf<Entity>()
    private val headers = mutableListOf(
        "# Generated by DTO-Codegen on ${Date()}",
        "",
        "from dataclasses import dataclass, field",
        "import typing as t",
    )

    override fun addEntity(entity: Entity) {
        if (!entities.contains(entity))
            entities.add(entity)
    }

    override fun addDtypeExtension(dtype: String, attrs: DtypeAttributesMapping) {
        dtypeAttrs[dtype] = attrs
    }

    private fun addHeader(str: String) {
        if (!headers.contains(str))
            headers.add(str)
    }

    private fun buildEntity(entity: Entity): String {
        val preLines = mutableListOf<String>()
        val lines = mutableListOf(
            "@dataclass",
            "class ${entity.name.camelCase()}:",
        )

        entity.description?.also {
            lines.add("    \"\"\"")
            lines.add("    " + entity.description)
            lines.add("    \"\"\"")
        }

        for (field in entity.fields) {
            val dtypeProps = dtypeAttrs[field.dtype]
            val fieldName = field.name.snakeCase()

            requireNotNull(dtypeProps) {"Missing extension for dtype '${field.dtype}'"}

            val attrs = dtypeProps.definitionArguments.toMutableMap()
            val isMarshmallowField = dtypeProps.definitionArguments.getOrDefault("metadata", "").contains("marshmallow")

            dtypeProps.requiredHeader?.let {
                addHeader(it)
            }

            var definition = dtypeProps.definition

            field.default?.let { raw ->
                dtypeProps.toGeneratedValue(raw).also {
                    if ("[".contains(it[0])) {
                        // complex value (list/map/etc) should be inserted via function above class
                        val callableName = "default_$fieldName"
                        preLines.add("def $callableName():")
                        preLines.add("    return $it\n\n")
                        attrs["default_factory"] = callableName
                    } else {
                        // simple value -> insert inline
                        attrs["default"] = it
                    }
                }
            }

            field.longDescription?.let {
                lines.add("    # $it")
            }

            if (field.nullable) {
                definition = "t.Optional[$definition]"

                if (isMarshmallowField)
                    field.metadata["allow_none"] = "True"

                if (field.default == null)
                    attrs["default"] = "None"
            }

            field.enum?.let {
                val choicesPrefix = (field.enumPrefix ?: fieldName).snakeCase().uppercase()
                val choicesName = "${choicesPrefix}S"
                val choices = it.keys.associate { key -> choicesPrefix + "_" + key.snakeCase().uppercase() to dtypeProps.toGeneratedValue(key) }
                val choicesDefinition = choices.map { entry -> "${entry.key} = ${entry.value}" }.joinToString(separator = "\n")
                preLines.add("$choicesDefinition\n$choicesName = [${choices.keys.joinToString()}]\n\n")

                if (isMarshmallowField)
                    field.metadata["validate"] = "[marshmallow_fields.validate.OneOf($choicesName)]"
            }

            // if field contains metadata, make "arg1=..., arg2=..." notation and replace "{metadata}" placeholder with it.
            val metaString = field.metadata.map { entry -> "${entry.key.snakeCase()}=${entry.value}" }.joinToString()
            attrs.forEach { entry -> attrs[entry.key] = entry.value.replace("{metadata}", metaString) }

            // include metadata into definition if needed
            if (dtypeProps.includeMetadataIntoDefinition)
                field.metadata.forEach { (key, value) -> attrs[key.snakeCase()] = value  }

            val expression = if (attrs.size == 1 && attrs.containsKey("default")) {
                // = defaultValue
                attrs.getValue("default")
            } else {
                // = field(param1=..., param2=...)
                val attrsString = attrs.map { entry -> "${entry.key}=${entry.value}" }.joinToString()
                "field($attrsString)"
            }

            lines.add("    ${field.name.snakeCase()}: $definition = $expression")
        }

        return (preLines + lines).joinToString("\n")
    }

    override fun build(): String {
        val builtEntities = entities.map { buildEntity(it) }

        return headers.joinToString("\n", postfix = "\n\n\n") +
                builtEntities.joinToString("\n\n\n", postfix = "\n")
    }
}