// Generated by DTO-Codegen
package org.codegen.generators

import java.time.Instant
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class EnumValue(val value: String) {
    @SerialName("value 1")
    VALUE_1("value 1"),
    @SerialName("value 2")
    VALUE_2("value 2"),
    @SerialName("value 3")
    VALUE_3("value 3"),
}

@Serializable
data class BasicDTO(
    @Contextual
    val timestamp: Instant,
    @SerialName("enum_value")
    val enumValue: EnumValue,
    // short description
    // very long description lol
    @SerialName("documented_value")
    val documentedValue: Double,
    @SerialName("optional_value")
    val optionalValue: Double = 0.0,
    @SerialName("nullable_value")
    val nullableValue: Boolean? = null,
)

/**
 * entity with all-singing all-dancing properties
 */
@Serializable
data class AdvancedDTO(
    val a: Int,
    val b: Int,
)
